- name: Startpage
  width: slim
  center-vertically: true
  columns:
    - size: full
      widgets:
        - type: search
          autofocus: true

        - type: monitor
          cache: 1m
          title: Services
          sites:
            - title: Jellyfin
              url: http://192.168.1.85:8096
              icon: si:jellyfin
            - title: JellyFindarr
              url: http://192.168.1.78:5505
              icon: si:joplin
            - title: qBittorrent
              url: http://192.168.1.85:8080
              icon: si:qbittorrent
            - title: Radarr
              url: http://192.168.1.85:7878
              icon: si:radarr
            - title: Sonarr
              url: http://192.168.1.85:8989
              icon: si:radarr
            - title: Lidarr
              url: http://192.168.1.85:8686
        - type: bookmarks
          groups:
            - title: Systems
              links:
                - title: Arch Linux Launchpad
                  url: http://192.168.1.227:9090
                - title: Arch Desk Launchpad
                  url: http://192.168.1.239:9090
                - title: Raspberry4 Launchpad
                  url: http://192.168.1.85:9090
            - title: Finance
              links:
                - title: pyNance Dashroad
                  url: http://192.168.1.239:3353
                - title: CapitalOne
                  url: https:capitalone.com
                - title: Fidelity
                  url: https://fidelity.com/
            - title: Other
              links:
                - title: OpenAI API Details
                  url: https://platform.openai.com/usage
                - title: Github
                  url: https://github.com/
                - title: ChatGPT
                  url: https://chatgpt.com/
                - title: Text Gen Webui
                  url: http://192.168.1.239:7860

